name: Update Bookmarks

on:
  push:
    paths:
      - 'workbeta/**'
  repository_dispatch:
    types: [google_sheets_update]
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours as a fallback
  workflow_dispatch:
jobs:
  update-bookmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install Dependencies
        run: |
          cd workbeta
          npm install googleapis
          
      - name: Update Bookmarks
        env:
          GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS}}
        run: |
          cd workbeta
          node generate-bookmarks.js
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add workbeta/bookmarks.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update bookmarks.json from Google Sheets" && git push)